#!/usr/bin/env bash
# Add the subdomain lb-01 to your domain, point it to your lb-01 IP
# Add the subdomain web-01 to your domain, point it to your web-01 IP
# Add the subdomain web-02 to your domain, point it to your web-02 IP

dns_ser() {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_ser "$1" "www"
  dns_ser "$1" "lb-01"
  dns_ser "$1" "web-01"
  dns_ser "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_ser "$1" "$2"
fi
