#!/usr/bin/env bash
# Write a Bash script that:
echo 'pgrep -f 100-process_and_pid_file' > /var/run/myscript.pid
while 'true'
do
	echo 'To infinity and beyond'
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "rm /var/run/myscript.pid"' SIGQUIT || SIGTERM
done
